// Function to create a greeting message with a given name
function createG(name) {
    return "Hello, " + name;
}

// Function to display a message generated by a provided function
function display(greetingFunction, userName) {
    // Call the provided function (greetingFunction) with the userName argument
    const message = greetingFunction(userName);
    return message; // Return the generated message
}

// Call the display function with createG as the greeting function and "Pppp" as the userName
var result = display(createG, "Pppp");

// Display the result in an alert
console.log(result);

while (i) {
    
}